export { default as SignUp } from './signup/signup'
export { default as Login } from './login/login'
export { default as RestaurantList } from './restaurant-list/restaurant-list'
export { default as FoodList } from './food-list/food-list'
export { default as DetailOrder } from './detail-order/detail-order'
export { default as OrderList } from './order-list/order-list'
export { default as AccountDetail } from './account-detail/account-detail'
